### ISSUE TITLE
Demo报错

### ISSUE THREAD

**Issue by mago960806** [CyberWon/DjangoCeleryDemo#1]
# 问题描述
python 3.7
pip install -r .\requirements.txt
安装了项目的依赖后，python manage runserver运行了项目，无报错信息。
打开首页点击按钮后端就有报错了。
![image](https://user-images.githubusercontent.com/18606660/43828025-f35065da-9b2d-11e8-870d-556e6ddee3d1.png)
报错内容是SyntaxError，所以很迷。
# 报错日志
```
Internal Server Error: /run
Traceback (most recent call last):
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Github\DjangoCeleryDemo-dev\demo\views.py", line 12, in run
    task = long_time_def.apply_async()
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\base.py", line 348, in send_task
    with self.producer_or_acquire(producer) as P:
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\base.py", line 403, in producer_or_acquire
    producer, self.amqp.producer_pool.acquire, block=True,
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\amqp.py", line 502, in producer_pool
    self.app.pool,
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\base.py", line 617, in pool
    self._pool = self.connection().Pool(limit=limit)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\celery\app\base.py", line 386, in connection
    'BROKER_CONNECTION_TIMEOUT', connect_timeout
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\kombu\connection.py", line 177, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\kombu\transport\__init__.py", line 109, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\kombu\transport\__init__.py", line 93, in resolve_transport
    return symbol_by_name(transport)
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\kombu\utils\__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\神船大法\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Github\DjangoCeleryDemo-dev\venv\lib\site-packages\kombu\transport\redis.py", line 815
    def _connparams(self, async=False, _r210_options=(
                              ^
SyntaxError: invalid syntax
```

**Comment by mago960806** [comment]
![image](https://user-images.githubusercontent.com/18606660/43828852-327b0b14-9b30-11e8-8962-05beedf229f8.png)

把所有语法错误全部修复后，又无限的跑任务，但没进度。

**Comment by mago960806** [comment]
![image](https://user-images.githubusercontent.com/18606660/43882620-db6835fa-9be2-11e8-8609-4d890c2e124c.png)
找到问题了，kombu库里有个async的包，但async是python内置的参数，导致冲突。出现语法错误。将async改为async_fixed即可解决问题
![image](https://user-images.githubusercontent.com/18606660/43882564-a83f0e1a-9be2-11e8-9994-1c977c293407.png)

**Comment by CyberWon** [comment]
哈哈。没看到。没进度那个问题是因为django 需要起来一个worker去异步跑那个任务，然后那个worker会把状态写到redis里面。
```
python manager.py celery worker
```
